language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '<2'
rvm:
  - 2.5
  - 2.6
  - 2.7
script: bundle exec rake
env:
  - RAILS_VERSION=6.0.3.5
  - RAILS_VERSION=5.2.0
services:
  - mysql
