name: CI

on:
  push: {}
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: github_ds_test
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
        rails-version: ['7.1.5', '7.2.2', '8.0.2']
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
